package org.everit.osgi.component.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The <code>Service</code> annotation defines whether and which service interfaces are provided by the component.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
@Documented
public @interface Service {

    /**
     * The class of the service interface provided by the component. If this property is not set provide elements will
     * be generated for all interfaces generated by the class
     */
    Class<?>[] value() default AutoDetect.class;

}
